FROM node:alpine

WORKDIR /usr/app

COPY package*.json ./
COPY prisma ./prisma/
COPY .env.example ./

RUN NODE_ENV=development yarn install

ARG TELEGRAM_TOKEN
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

ENV TELEGRAM_TOKEN ${TELEGRAM_TOKEN}
ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DB}

COPY . .

RUN touch .env && yarn build

CMD ["yarn", "start"]